/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim': 'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright': 'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        onsurface: 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'inverse-surface': 'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface': 'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        outline: 'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',

        primary: {
          DEFAULT: '#2563eb',
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-on-primary) / <alpha-value>)',

        accent: {
          DEFAULT: '#0ea5e9',
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
        },

        secondary: '#475569',
        'on-secondary': '#ffffff',
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        tertiary: '#64748b',
        'on-tertiary': '#ffffff',
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--color-on-tertiary-container) / <alpha-value>)',

        error: '#dc2626',
        'on-error': '#ffffff',
        'error-container': 'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--color-on-error-container) / <alpha-value>)',
        warning: '#d97706',
        'on-warning': '#ffffff',
        'warning-container': 'rgb(var(--color-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--color-on-warning-container) / <alpha-value>)',
        success: '#059669',
        'on-success': '#ffffff',
        'success-container': 'rgb(var(--color-success-container) / <alpha-value>)',
        'on-success-container': 'rgb(var(--color-on-success-container) / <alpha-value>)',
        info: '#2563eb',
        'info-container': 'rgb(var(--color-info-container) / <alpha-value>)',
        'on-info-container': 'rgb(var(--color-on-info-container) / <alpha-value>)',

        background: 'rgb(var(--color-background) / <alpha-value>)',
        'surface-variant': 'rgb(var(--color-surface-variant) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        sm: '0.5rem',
        md: '0.625rem',
        lg: '0.75rem',
        xl: '0.875rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
        '3xl': '64px',
        gutter: '24px',
        'container-max': '1440px',
      },
      fontFamily: {
        'display-lg': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'display-md': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-sm': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-md': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-sm': ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['44px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-md': ['32px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.3', fontWeight: '500' }],
      },
      boxShadow: {
        'soft-xs': '0px 1px 2px rgba(15, 23, 42, 0.04)',
        'soft-sm': '0px 1px 3px rgba(15, 23, 42, 0.06), 0px 1px 2px rgba(15, 23, 42, 0.04)',
        'soft-md': '0px 2px 6px -1px rgba(15, 23, 42, 0.07), 0px 1px 2px rgba(15, 23, 42, 0.04)',
        'soft-lg': '0px 6px 16px -4px rgba(15, 23, 42, 0.09), 0px 2px 6px -2px rgba(15, 23, 42, 0.05)',
        'soft-xl': '0px 16px 40px -12px rgba(15, 23, 42, 0.14), 0px 4px 12px -4px rgba(15, 23, 42, 0.06)',
        'soft-2xl': '0px 24px 64px -16px rgba(15, 23, 42, 0.20), 0px 4px 16px -8px rgba(15, 23, 42, 0.08)',
        ring: '0 0 0 4px rgba(37, 99, 235, 0.14)',
        'card-hover': '0px 8px 24px -10px rgba(15, 23, 42, 0.16), 0px 2px 6px -2px rgba(15, 23, 42, 0.06)',
      },
      keyframes: {
        'gradient-shift': {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.55' },
        },
        'shimmer': {
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        'gradient-shift': 'gradient-shift 16s ease infinite',
        'fade-in': 'fade-in 0.4s ease-out forwards',
        'pulse-soft': 'pulse-soft 2.5s ease-in-out infinite',
        shimmer: 'shimmer 1.6s infinite',
      },
    },
  },
  plugins: [],
}